services:
  - type: web
    name: monazamti-plus
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: change-this-secret
      - key: DATABASE_URL
        fromDatabase:
          name: monazamti-plus-db
          property: connectionString
    plan: free
    autoDeploy: true
    pullRequestPreviewsEnabled: true

databases:
  - name: monazamti-plus-db
    plan: free
    databaseName: site_db
    user: site_db_owner
    ipAllowList: []
