services:
  - type: web
    name: project-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    branch: main # التحديث من الفرع الرئيسي
    autoDeploy: true # تفعيل النشر التلقائي
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: eng.mohamed0shaban@gmail.com
      - key: ADMIN_PASSWORD
        value: Mm123456789

databases:
  - name: project_db
    databaseName: project_management
    user: admin
    plan: free
